### PR TITLE
Test staging

### PR DESCRIPTION
**Pull request by Antoine-Zimmermann**
Fixed font issue by reusing cmss8. Fixed double-quote problem using `<code>` for literals. Fixed cedilla issue with Gonçalves. I added the correction to navigational queries in the test-staging branch.

### CODE REVIEW

**Comment by Antoine-Zimmermann** [comment]
@aidhog please review the changes. @miselico how do we deal with index.html? I think it's supposed to be generated automatically now in the main branch, so should we simply remove it from the test-staging branch?

**Review by aidhog — APPROVED** [review]

**Review by aidhog — APPROVED** [review]
Would not be the easiest to edit in future, but if I looks okay ...

**Review by aidhog — APPROVED** [review]

**Review by aidhog — APPROVED** [review]

**Comment by aidhog** [comment]
Reviewed! I guess I should no longer be pushing edits to the main branch? :)

**Comment by miselico** [comment]
@Antoine-Zimmermann @aidhog 

Indeed, better to not push to main directly, I would even suggest to disable that.

When you push to your own branches, the page gets build automatically and that outcome is pushed to https://github.com/Knowledge-Graphs-Book/HTML-Book-staging

This is also hosted, but somewhat hidden. If the branch was called `myfancyname`, then you can find the book online from `https://knowledge-graphs-book.github.io/HTML-Book-staging/myfancyname/`

I had made this test test-staging branch for testing this out.. it works for any branch name. But, this is now deployed on https://knowledge-graphs-book.github.io/HTML-Book-staging/test-staging/

So, the way to work on the book becomes

1. Make a branch
2. Make all changes you want on the branch
3. Push to github
4. Wait for the build to finish (you can check the status in the actions tab, usually less than a minute)
5. Preview the page
6. Make a pull request to merge into main

**Comment by Antoine-Zimmermann** [comment]
Thanks Aidan for the review. Thanks Michael for the clarification. Why do you say:

> Would not be the easiest to edit in future, but if I looks okay ...

**Comment by miselico** [comment]
Just a clarification. There is no need to ever include the index.html file in the repository. It is automatically generated and deployed.

**Pull request merged**
